### ISSUE TITLE
Missing "Spanish" language label on Administrative page

### ISSUE THREAD

**Issue by aatmns** [EIDSS/EIDSSDemo#2]
Bug
User: chief veterinarian
Section: EIDSS home page.
Browser: Chrome
When Administrative page is opened in English language, the label "Spanish" is missing. 
![spanish_label_missing](https://user-images.githubusercontent.com/32458032/31121792-9c4dc6f2-a807-11e7-9760-b81f05ccef97.JPG)
Additionally, if switching to English language, the Spanish label appears. 
Also, the same behavior happens when selecting Russian language - Spanish label is missing.

**Comment by aatmns** [comment]
Дополнительно, данное поведение не постоянно.

**Comment by aatmnv** [comment]
This is a bug that needs to be considered by our Dev Team. Have you tried to replicate this behavior on other browsers? Firefox, or IE, perhaps?

**Comment by aatmns** [comment]
Yes I saw I the same issue on Firefox. Need to retest on IE.


-------- Original message --------

**Comment by aatmns** [comment]
Just tested on IE 11. The same issue is there as well. Spanish label is missing by default, but it comes back when "English" is selected again.

**Comment by aatmnv** [comment]
Thank you, that was very helpful. We are documenting this as a software
defect  and will inform about the fix. Anatoliy

**Comment by aatmnv** [comment]
Our Dev Team just completed the fix for the "Spanish" label bug. We found a missing string in the CSS file. Please verify that it is addressed.

**Comment by aatmns** [comment]
Verified. It works properly now on all four browsers. Safari, IE12, Firefix, Chrome. Thank you.

**Comment by aatmns** [comment]
I just noticed that the issue is still with Edge. Do you want to look into that?

**Comment by aatmnv** [comment]
Thank you. We are taking additional effort to see this issue with Microsoft Edge. Still we suggest to use Firefox, Chrome, IE, and Safari to work with EIDSS. The issue is closed. Anatoliy
